<?php
/**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.1
 */
?>
<?php
$block = $this->getItems($this->getBlockCode());
if($block){
    $sliderCode = $block->getSliderCode();
}

?>

<?php if ($block && $block->getSlides() && $block->getSlides() != '[]'): ?>
    <div id="gomage-slider-block-<?php echo $sliderCode; ?>"
        <?php echo ($block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::MOUSE) ? 'class="gps-arrows-hover gomage-slider-block-' . $block->getSliderCode() . '"' : 'class="gomage-slider-block-' . $block->getSliderCode() . '"'; ?>>
        <?php if ($block->getNavigationBarAlignment() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::TOP
            &&
            ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::SIDEBAR
                ||
                $block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO)
        ): ?>
            <div class="gomage-slider-sidebar gomage-slider-sidebar-<?php echo GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::getClassName($block->getNavigationBarAlignment()); ?>" <?php echo ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO) ? 'style="display: none;"' : ''; ?>>
                <?php echo $this->getSidebarHtml($block, $sliderCode); ?>
            </div>
        <?php endif; ?>
        <div class="gomage-slider-container">
            <div class="gomage-slider-content">
                <?php echo $this->getContentHtml($block, $sliderCode); ?>
            </div>
        </div>
        <?php if ($block->getNavigationBarAlignment() != GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::TOP
            &&
            ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::SIDEBAR
                ||
                $block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO)
        ): ?>
            <div
                class="gomage-slider-sidebar gomage-slider-sidebar-<?php echo GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::getClassName($block->getNavigationBarAlignment()); ?>" <?php echo ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO) ? 'style="display: none;"' : ''; ?>>
                <?php echo $this->getSidebarHtml($block, $sliderCode); ?>
            </div>
        <?php endif; ?>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        new GomageSliderClass({
            config:<?php echo $this->getConfig(); ?>,
            slides:<?php echo $this->getSlidesJson($this->getBlockId($this->getBlockCode())); ?>,
            slider_code: '<?php echo $sliderCode; ?>',
            auto_start: <?php echo  $block->getEnableAutostart();?>
        });

        //]]>
    </script>
<?php endif; ?>