<?php
/**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.2
 */
?>
<?php
    $slider_code = $this->getSliderCode();
    $block = $this->getBlock();
?>

<?php if ($block && count($this->getSlides())): ?>
    <div id="gomage-slider-block-<?php echo $slider_code; ?>"
         class="gomage-slider-block-<?php echo $block->getCode(); ?> <?php if ($block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::MOUSE): ?>gps-arrows-hover<?php endif; ?>">
        <?php if (in_array($block->getNavigationBarAlignment(),
                array(GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::TOP,
                      GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::LEFT,
                      GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::RIGHT)) &&
            ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::SIDEBAR ||
             $block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO) ): ?>
            <div class="gomage-slider-sidebar gomage-slider-sidebar-<?php echo GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::getClassName($block->getNavigationBarAlignment()); ?>" <?php echo ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO) ? 'style="display: none;"' : ''; ?>>
                <?php echo $this->getSidebarHtml(); ?>
            </div>
        <?php endif; ?>
        <div class="gomage-slider-container">
            <div class="gomage-slider-content">
                <?php echo $this->getContentHtml(); ?>
                <?php echo $this->getNavigationbarHtml(); ?>
            </div>
        </div>
        <?php if ($block->getNavigationBarAlignment() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::BOTTOM &&
            ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::SIDEBAR ||
             $block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO)): ?>
            <div class="gomage-slider-sidebar gomage-slider-sidebar-<?php echo GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Alignment::getClassName($block->getNavigationBarAlignment()); ?>" <?php echo ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::NO) ? 'style="display: none;"' : ''; ?>>
                <?php echo $this->getSidebarHtml(); ?>
            </div>
        <?php endif; ?>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        new GomageSliderClass({
            config:<?php echo $this->getConfig(); ?>,
            slides:<?php echo $this->getSlidesJson(); ?>,
            slider_code: '<?php echo $slider_code; ?>'
        });
        //]]>
    </script>
<?php endif; ?>