<?php
/**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2014 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.2
 */
?>
<?php
    $slider_code = $this->getSliderCode();
    $block = $this->getBlock();
    $slides = $this->getSlides();
    $slide = array_shift($slides);
    $helper = Mage::helper('gomage_slider');
?>

<?php if ($block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::ALWAYS ||
          $block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::MOUSE): ?>
    <div class="gps-arrow gomage-arrow-left">
        <a class="left-<?php echo $slider_code; ?>" href="javascript:void(0)">
            <span><?php echo $this->__('Previous') ?></span>
        </a>
    </div>
<?php endif; ?>

<div class="gomage-content-item">
    <div class="gomage-image-container">
        <div class="gomage-content-image">
            <a id="slide-id-<?php echo $slider_code; ?>"
               class="slide-id-<?php echo $slider_code; ?>" <?php echo $slide->openSliderLinkInBlank(); ?>
               <?php if ($slide->getSliderLink() != ''): ?>href="<?php echo $slide->getSliderLink(); ?>"<?php endif; ?>>
                <img class="gs-img-<?php echo $slider_code; ?>"
                    alt="<?php echo $slide->getAltText(); ?>"
                    src="<?php echo Mage::getBaseUrl('media') . 'slider/' . $slide->getImage(); ?>"/>
            </a>
        </div>
    </div>

    <?php if ($slide->getShowSliderText()): ?>
        <div class="gomage-content-container">
            <div class="gomage-content gomage-content-<?php echo $slider_code; ?>">
                <div class="gomage-content-text-bg"
                     style="<?php echo $helper->getSlideTextBgStyle($slide, $block); ?>"></div>
                <div class="gomage-content-text" style="<?php echo $helper->getSlideTextStyle($slide, $block); ?>">
                    <?php echo $slide->getSliderText(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php if ($block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::ALWAYS ||
          $block->getShowArrows() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrows::MOUSE): ?>
    <div class="gps-arrow gomage-arrow-right">
        <a class="right-<?php echo $slider_code; ?>"
           href="javascript:void(0)"><span><?php echo $this->__('Next') ?></span>
        </a>
    </div>
<?php endif; ?>

<?php if ($block->getShowPauseButton()): ?>
    <div class="gomage-play-pause <?php if($block->getEnableAutostart()): ?>gomage-pause<?php else: ?>gomage-play<?php endif ?> gomage-play-pause-<?php echo $slider_code; ?>">
        <a class="play-pause-<?php echo $slider_code; ?>" href="javascript:void(0)" title="<?php echo $this->__('Pause') ?>">
            <span></span><span></span>
        </a>
    </div>
<?php endif; ?>



