<?php
 /**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.3
 */
?>
<?php
    $slider_code = $this->getSliderCode();
    $block = $this->getBlock();
    $slides = $this->getSlides();

    $i = 1;
    $navigation_bar_style = GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::toOptionHash();
?>

<?php if ($block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::CIRCLE ||
	      $block->getShowNavigationBar() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Show::SQUARE): ?>
    <ul class="navigation-bar-list navigation-bar-<?php echo $navigation_bar_style[$block->getShowNavigationBar()]; ?> ">
        <?php foreach( $slides as $_order => $_slide ): ?>
            <li id="slide-order-<?php echo $slider_code; ?>-<?php echo $_order;?>" data-id="<?php echo $_order; ?>" class="sidebar-link gs-<?php echo $slider_code; ?> <?php echo ( $i == 1 ) ? 'active' : ''; ?>"></li>
            <?php $i++; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>