<?php
 /**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.1
 */
?>
<?php
    $slider_code = $this->getSliderCode();
    $block = $this->getBlock();
    $slides = $this->getSlides();
    $i = 1;
?>
<?php foreach( $slides as $_order => $_slide ): ?>
    <div id="sidebar-item-order-<?php echo $slider_code ;?>-<?php echo $_order; ?>" class="gomage-sidebar-item-<?php echo $slider_code; ?> <?php echo ( $i == 1 ) ? 'active' : ''; ?>">
        <a href="javascript:void(0)" id="slide-order-<?php echo $slider_code; ?>-<?php echo $_order; ?>" data-id="<?php echo $_order; ?>" class="sidebar-link gs-<?php echo $slider_code; ?>"><?php echo $_slide->getSidebarContent(); ?></a>
    </div>
	<?php $i++; ?>
<?php endforeach; ?>