<?php
 /**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2012 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.1
 */
?>
<?php 
	$item = $this->getItem();
	$slides = $this->getSlides();
    $_slide = $slides[$item->getId()];
    $_slide = array_values($_slide);
    $_slide = array_shift($_slide);
?>
<?php
if ( isset( $slides[$item->getId()] ) ):
	$i = 0;
	foreach( $slides[$item->getId()] as $_order => $_item ):
	?>
		<div id="sidebar-item-order-<?php echo $this->slider_code ;?>-<?php echo $_order; ?>" class="gomage-sidebar-item-<?php echo $this->slider_code ;?> <?php echo ( $i == 0 ) ? 'active' : ''; ?>">
			<a href="javascript:void(0)" id="slide-order-<?php echo $this->slider_code ;?>-<?php echo $_order;?>" data-id="<?php echo $_order;?>" class="sidebar-link gs-<?php echo $this->slider_code ;?>"><?php echo $_item->getSidebarContent(); ?></a>
		</div>
	<?php 
	$i++;
	endforeach;
endif;
?>