<?php
 /**
 * GoMage Slider Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.3
 */
?>
<?php
    $helper = Mage::helper('gomage_slider');
?>
<style type="text/css">

<?php foreach ($this->getBlocks() as $block): ?>
	   .gomage-slider-block-<?php echo $block->getCode() ?>{
			<?php echo $block->blockCss(); ?>
  	   }
       .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-content{
			float: left;
  	   }
	   .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-slider-container{
			<?php echo $block->containerCssStyle(); ?>
  	   }
	   .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-slider-sidebar{
			<?php echo $block->sideBarCss(); ?>
  	   }
	   .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-sidebar-item{
			<?php echo $block->sideBarBlockCss(); ?>
  	   }

    /* Arrow Color
    -------------------------------------------------- */
      /* Left Arrow */
     .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-arrow-left span{
        border-right-color: <?php echo $helper->formatColor($block->getArrowColor()); ?>;
     }
      /* Right Arrow */
     .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-arrow-right span{
        border-left-color: <?php echo $helper->formatColor($block->getArrowColor()); ?>;
     }

    /* Mouse Over Arrow Color
    -------------------------------------------------- */
      /* Left Arrow */
     .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-arrow-left:hover span{
        border-right-color: <?php echo $helper->formatColor($block->getMouseOverColor()); ?>;
     }
      /* Right Arrow */
     .gomage-slider-block-<?php echo $block->getCode() ?> .gomage-arrow-right:hover span{
        border-left-color: <?php echo $helper->formatColor($block->getMouseOverColor()); ?>;
     }

	<?php if ( $block->getArrowsType() == GoMage_Slider_Model_Adminhtml_System_Config_Source_Navigation_Arrowstype::STYLE2 ): ?>
      /* Mouse Over Background Color
      -------------------------------------------------- */
      .gomage-slider-block-<?php echo $block->getCode() ?> .gps-arrow:hover{
        background: <?php echo $helper->formatColor($block->getMouseOverBackground()); ?>;
      }
	<?php endif; ?>

<?php endforeach; ?>

</style>
